### ISSUE TITLE
Option NOT to convert to paths and ONLY flatten transforms?

### ISSUE THREAD

**Issue by rulatir** [stadline/svg-flatten#1]
A utility capable of completely flattening transforms and baking them into point geometry WITHOUT changing element types is something that seems to be altogether missing from the known Universe. I've googled high and low and there is literally no software in existence (or at least no software cheaper than my house) capable of doing that.

Since your utility already does transform flattening, adding an option to NOT do the other thing that it currently does should be straightforward and would be positively awesome.

**Comment by alex-pex** [comment]
How to you apply transforms on basic shapes? It works for scaling or translate, but with more advanced transforms like skewX it seems impossible
![image](https://github.com/stadline/svg-flatten/assets/368155/cc0d14ee-a582-4640-91c6-0e7a1197f47b)

Moreover, I don't maintain this lib anymore, except if someone is willing to make a pull request
