### ISSUE TITLE
Start documentation

### ISSUE THREAD

**Issue by jvolker** [stadline/svg-flatten#2]
Maybe start the documentation with this Node.js example to show at least one way of using it?

```js
const svgFlatten = require('svg-flatten')
const fs = require('fs')

let flattendSvgPath = 'tmp-flattened.svg'

// read SVG file into string
let svgString = fs.readFileSync('circle-rect.svg', 'utf8')
// convert all objects to paths 
let modifiedSvgString = svgFlatten(svgString).pathify().value()
// write SVG string to disk
fs.writeFileSync(flattendSvgPath,modifiedSvgString)
```

**Comment by Alex-Anev** [comment]
> write library
> refuse to elaborate
> leave

real sigma shit

**Comment by alex-pex** [comment]
I released a new version with https://github.com/stadline/svg-flatten/pull/4 and an updated documention. Enjoy
(thanks for the small example @jvolker and sorry for being so late to see this issue)
